export const GridWidth = 1300
export const GridHeight = 400
export const Straights = 36
export const StraightsRows = 3
export const Dozens = 3
export const Columns = 3
export const BottomCells = 6
export const StraightYPortion = 0.25
export const GridXYportion = 1
export const ColumnXportion = 0.65
export const ZeroXportion = 0.7
export const DozensText = ['1st 12', '2nd 12', '3nd 12']
export const BottomCellsText = ['1 to 18', 'EVEN', '', '', 'ODD', '19 to 36']