export let GridWidth = 1300
export let GridHeight = 400
export const Straights = 36
export const StraightsRows = 3
export const Dozens = 3
export const Columns = 3
export const BottomCells = 6
export const StraightYPortion = 0.25
export const GridXYportion = 1
export const ColumnXportion = 0.65
export const ZeroXportion = 0.7
export const DozensText = ['1st 12', '2nd 12', '3nd 12']
export const BottomCellsText = ['1 to 18', 'EVEN', '', '', 'ODD', '19 to 36']
export const DozenYportion = (GridXYportion - (3 * StraightYPortion)) / 2
export const BottomCellYportion = DozenYportion
export const straightWidth = GridWidth / (ZeroXportion + (Straights / StraightsRows) + ColumnXportion)
export const BottomCellXportion = (GridXYportion - StraightYPortion * 3) / 2
export const dozenWidth = 4 * straightWidth
export const dozenHeight = GridHeight * DozenYportion
export const bottomCellWidth = straightWidth * 2
export const bottomCellHeight = GridHeight * BottomCellYportion
export const zeroWidth = straightWidth * ZeroXportion
export const columnWidth = ColumnXportion * straightWidth
export const bottomCellsCoords: Array<coords> = []
export const columnsCoords: Array<coords> = []
export const dozensCoords: Array<coords> = []
export const straightsCoords: Array<coords> = []
export const firstColumnCoords = [zeroWidth + straightWidth * 12, 0]
export const zeroCoords = [[0, 0]]
type coords = Array<number>