export const GridWidth = 600
export const GridHeight = 150
export const Straights = 36
export const StraightsRows = 3
export const Dozens = 3
export const Colums = 3
export const BottomCells = 6
export const ColumnWidth = 0.5
export const ZeroWidth = 1
export const DozensText = ['1st 12', '2nd 12', '3nd 12']
export const BottomCellsText = ['1 to 18', 'EVEN', '', '', 'ODD', '19 to 36']