export const GreedWidth = 600
export const GreedHeight = 150
export const NumberOfSquareCells = 36
export const NumberOfSquereCellsRows = 3
export const CoordinatesOfFirstSquareCell = [0, 100]
export const SquereCellWidth = GreedWidth / 12
export let NumberOfDozensCells = 3
export let DozensText = ['1st 12', '2nd 12', '3nd 12']
export let BottomCellsText = ['1 to 18', 'EVEN', '', '', 'ODD', '19 to 36']
export let NumberOfBottomCells = 6
export let SquareCellWidth = GreedWidth / (NumberOfSquareCells / NumberOfSquereCellsRows)
export let DozenCellWidth = GreedWidth / NumberOfDozensCells
export let BottomCellWidth = GreedWidth / NumberOfBottomCells